name: flutter_staff
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.0.0
  bloc: ^8.0.0
  equatable: ^2.0.3
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  workmanager: ^0.5.2
  flutter_timezone: ^3.0.0
  flutter_native_timezone: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.0.0
  build_runner: ^2.0.0
  flutter_launcher_icons: ^0.14.1
  

flutter:
  uses-material-design: true

  assets:
    - assets/icons/background_logo.png
    - assets/icons/icon_S.png


flutter_launcher_icons:
  android: "logo"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
